### PR TITLE
fix: invalid image height fixed

### LINKED ISSUE #95: issue: Image with src "/images/twitter-clone.jpg" has invalid "height" property. Expected a numeric value in pixels but received "fit-content".
**Describe the bug**
Getting this error after yarn dev on localhost:3000:-
Image with src "/images/twitter-clone.jpg" has invalid "height" property. Expected a numeric value in pixels but received "fit-content".

**To Reproduce**
1. Go to ' localhost after running yarn dev '

**Expected behavior**
we should not get this error 

**Screenshots**
Screenshot (165)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]

### PR DESCRIPTION
**Pull request by VedP20**
fix: Image with src "/images/twitter-clone.jpg" has invalid "height" property. Expected a numeric value in pixels but received "fit-content".
Fixes #95

Screenshot (166)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ X] Test A - Simply run yarn dev and you will be able to see the main page without any issue or error related to image height

## Mandatory Tasks

- [ X ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: components/UI/PortfolioItem.jsx [hunk 1]
```diff
@@ -15,31 +15,33 @@ const PortfolioItem = (props) => {
   return (
     <div className={`${classes.portfolio__item}`}>
       <a
-        target="_blank"
-        style={{ textDecoration: "none" }}
+        target='_blank'
+        style={{ textDecoration: 'none' }}
         href={liveUrl}
```
Comment (TheMohit2003) [inline components/UI/PortfolioItem.jsx:20]: Please use double quotes and not single quotes as the entire codebase has double quotes. This will keep the code uniform and clean.

Comment (Wmg20) [reply components/UI/PortfolioItem.jsx:20]: Sure, I will
