### PR TITLE
fix: 'Blogs link'(different url) in the navbar opens in different page

### LINKED ISSUE #177: [Bug]: 'Blogs' link in the navbar (different URL) opens in the same webpage
### Describe the bug

**`Opening links with different URLs on another webpage` are standard practice.**

But, when we click on the `Blogs` link in the navigation bar, the website opens up on the same page. The new blog website has no direct link to the original website through which users can navigate to other sections of the page.

Hence, a better alternative will be to open `Blogs` on another webpage.

### To Reproduce

1. Go to the [website](https://www.piyushgarg.dev/).
2. Click on 'Blogs' in the navigation bar.

It will open `https://blog.piyushgarg.dev/` on the same page.

### Expected behavior

The `Blogs` link should open `https://blog.piyushgarg.dev/` on another page so that the user will have the option to explore other sections of the page.

### Screenshots/Videos

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/76887609/33577df1-0c31-4acf-a93c-23a601ba4baf

### Additional context

_No response_

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

### PR DESCRIPTION
**Pull request by deependujha**
## What does this PR do?

Added a conditional statement in the navbar link tag, if the link text is going to be `Blogs`, open it on another page, else do as before.

**Motivation behind this:**
The `Blogs` link in the navbar had a different URL and once the user clicks on it, the new webpage opens on the same page. The blog website had no direct link to the original website and there was no way for users to visit other sections of the original website except manually going back.

Fixes #177

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/76887609/566ff258-bcc2-44fd-92f4-95a70745dc9d

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Open the website.
- Click on all the different navigation links in the navbar.
- Only `Blogs` link will open in another tab, rest all will open in the same webpage.

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: components/Header/Header.jsx [hunk 1]
```diff
@@ -108,11 +108,11 @@ const Header = () => {
                   key={index}
                   className={`${classes.mobile__menuDiv} cursor-pointer`}
                 >
-                  <Link aria-label={item.display} href={item.path}>
+                  <Link aria-label={item.display} href={item.path} target={`${item.display==='Blogs'?'_blank':'_self'}`}>
```
Comment (piyushgarg-dev) [inline components/Header/Header.jsx:111]: Don't hard code the logic based on the display text 👀

**Review by piyushgarg-dev — CHANGES_REQUESTED** [review]
